/* Program by: Tiffani Shilts Winter 2020. This program is c99 compliant.
    Multi Queue Generator: This program receives input from the user via argc and argv. User is allowed to provide:
    -q number of queues, -r number of requests (number of items to place in queues), -min the minimum value of random
    numbers generated for queue, and -max the maximum value of random numbers generated for queue. Given these inputs,
    program iterates through the number of requests, randomly distributing randomly generated numbers among queues.
    Program then prints out the sum of every queue requested to generate, and the values contained in the lowest sum
    queue. Empty queues are considered to have a sum of zero. Default numbers generated by the program if the user does
    not specify are: 1 queues, 5 requests, 0 min, and 20 max. Program uses integer number of seconds from system clock to
    generate different values every time program is ran */

#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <string.h>

int main (int argc, char *argv[])
{
    char queue[] = "-q";        // creating flag string variables for strcmp
    char requests[] = "-r";
    char minimum[] = "-min";
    char maximum[] = "-max";

    // initialize default numbers
    // default queue #: 1
    // default request #: 5
    // default min #: 0
    // default max #: 20

    int q = 1;                  // setting default values
    int r = 5;
    int min = 0;
    int max = 20;

    int randomQueueIndex;       // random queue to place requests in

    for(int i = 0; i < argc; i++)  // replacing arguments with flags found in argv array
    {
        if(strcmp(queue, argv[i]) == 0)
        {
            q = atoi(argv[i+1]);
        }
        else if(strcmp(requests, argv[i]) == 0)
        {
            r = atoi(argv[i+1]);
        }
        else if(strcmp(minimum, argv[i]) == 0)
        {
            min = atoi(argv[i+1]);
        }
        else if(strcmp(maximum, argv[i]) == 0)
        {
            max = atoi(argv[i+1]);
        }
    }

    typedef struct queue        // Queue structure
    {
        int length;             // queue array index number
        int sum;                // sum of array numbers
        int* arr;               // pointer to queue array
    } Q;

    srand(time(0));     // use real time to create more random seed (different numbers every run

    Q** queueArray = (Q**)(malloc(sizeof(Q*) * q));   // create array instance of struct

    for(int i = 0; i < q; i++)      // iterate through # of queues
    {
        queueArray[i] = (Q*) malloc(sizeof(Q));    // Allocate memory for struct
        queueArray[i]->length = 0;                 // number of items in queue
        queueArray[i]->sum = 0;                    // sum value for each queue
        queueArray[i]->arr = (int*)malloc(sizeof(int) * r);     //allocate memory for queue array
    }

    for(int i = 0; i < r; i++)      // iterate through # of requests
    {
        randomQueueIndex = rand() % q;                          // choose a queue to put arrays in randomly
        Q * currentQueue = queueArray[randomQueueIndex];        // creating pointer
        if(max == 1)
        {
        currentQueue->arr[currentQueue->length++] = rand() % 2;     // special case
        }
        currentQueue->arr[currentQueue->length++] = rand() % max + min;     // add one random value to random queue and increment its array index
    }

    for(int i = 0; i < q; i++)          // iterate through # of queues
    {
        for (int j = 0; j < queueArray[i]->length; j++) // iterate through array in queue
        {
            queueArray[i]->sum += queueArray[i]->arr[j]; // add each array # together
        }
    }

    int lowestSum = queueArray[0]->sum;     // set first array number as lowest sum
    int lowestSumQueueNumber = 0;           // initialize queue number to zero
    for(int k = 1; k < q; k++)              // iterate through # of queues
    {
        if(queueArray[k]->sum <= lowestSum) // if new lowest sum found
        {
            lowestSum = queueArray[k]->sum; // replace the old one
            lowestSumQueueNumber = k;       // remember its queue number

        }
    }
    for(int i = 0; i < q; i++)
    {
        printf("Queue %d sum: %d \n", (i+1), queueArray[i]->sum);     // print all queue sums
    }

    printf("\n");
    printf("Values in lowest sum queue:\n");
    int len = queueArray[lowestSumQueueNumber]->length;

    if(len == 0)    // if array is empty, tell user
    {
        printf("\nQueue is empty.");
    }

    else
    {
        for(int i = 0; i < len; i++)    // iterate through array of lowest sum
        {
            printf((i == len - 1)?" %d":" %d,", queueArray[lowestSumQueueNumber]->arr[i]);  // if statement does not print comma for last number in array
        }
    }
    printf("\n");
}
